# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
        ('lists', '0006_auto_20200607_1711'),
    ]

    operations = [
    ]
